Repository wecode-bootcamp-korea/13-aircnb-frontend, pull requests merged in 2020-11, with the labels that each got.

#1 [Air Cnb 신은선] Add: Home Details Page 레이아웃 추가
  src/Pages/HomeDetails/Component/Rule.js
  src/Pages/HomeDetails/Data/RULES_DATA.js
  src/Pages/HomeDetails/HomeDetails.js
  src/Routes.js
Labels: Status: 추가 기능 구현중

#3 [13기 정양효 ] Add: 필터 기능용 컴포넌트 파일 생성
  package-lock.json
  package.json
  src/Pages/HomeList/Components/Card.js
  src/Pages/HomeList/Components/Filters/CancellationFlexibility.js
  src/Pages/HomeList/Components/Filters/InstantBook.js
  src/Pages/HomeList/Components/Filters/MoreFilters.js
  src/Pages/HomeList/Components/Filters/Price.js
  src/Pages/HomeList/Components/Filters/RoomsAndBeds.js
  src/Pages/HomeList/Components/Filters/TypeOfPlace.js
  src/Pages/HomeList/Components/GoogleMap.js
  src/Pages/HomeList/HomeList.js
Labels: Status: 수정 요청

#4 [Air Cnb 신은선] Add: homeDetails Page 레이아웃 완성
  =#.##
  package-lock.json
  package.json
  public/data/detail_data.json
  public/index.html
  src/Pages/HomeDetails/Component/Bed.js
  src/Pages/HomeDetails/Component/BedType.js
  src/Pages/HomeDetails/Component/BookingBox.js
  src/Pages/HomeDetails/Component/BookingBoxCalendar.js
  src/Pages/HomeDetails/Component/BookingBoxPersonnel.js
  src/Pages/HomeDetails/Component/CalendarStyling.scss
  src/Pages/HomeDetails/Component/Facilities.js
  src/Pages/HomeDetails/Component/Facility.js
  src/Pages/HomeDetails/Component/HomeImgCon.js
  src/Pages/HomeDetails/Component/HostInfo.js
  src/Pages/HomeDetails/Component/ImgCarouselCon.js
  src/Pages/HomeDetails/Component/MapContent.js
  src/Pages/HomeDetails/Component/ModalPortal.js
  src/Pages/HomeDetails/Component/Notice.js
  src/Pages/HomeDetails/Component/NoticeData.js
  src/Pages/HomeDetails/Component/Notices.js
  src/Pages/HomeDetails/Component/Review.js
  src/Pages/HomeDetails/Component/ReviewModal.js
  src/Pages/HomeDetails/Component/Reviews.js
  src/Pages/HomeDetails/Component/Rule.js
  src/Pages/HomeDetails/Component/WishList.js
  src/Pages/HomeDetails/Component/WishListCon.js
  src/Pages/HomeDetails/Component/slickSlider.scss
  src/Pages/HomeDetails/Data/RULES_DATA.js
  src/Pages/HomeDetails/HomeDetails.js
  src/Routes.js
Labels: Status: Conflict 해결 요청, Status: 수정 요청, Status: 추가 기능 구현중

#2 [13기 백경민] HomeBooking Page 레이아웃 완성
  #.##
  .vscode/settings.json
  debug.log
  package-lock.json
  package.json
  public/data/HomeBookingData.json
  public/index.html
  src/Pages/HomeBooking/Calendar.js
  src/Pages/HomeBooking/Calendar.scss
  src/Pages/HomeBooking/HomeBooking.js
  src/Pages/HomeBooking/Modal.js
  src/Pages/HomeBooking/Payment.js
  src/Pages/HomeBooking/ToggleSwitch.js
  src/Routes.js
Labels: Status: Accepted

#10 [13기 강수명 aircnb] 메인 페이지 구현
  package-lock.json
  src/Components/ProfileMenuList/Login/Login.Styled.js
  src/Components/ProfileMenuList/Login/Login.js
  src/Components/Search/Guest/Guest.Styled.js
  src/Components/Search/Location/Location.Styled.js
  src/Components/Search/Search.Styled.js
  src/Images/Main/desert.svg
  src/Images/Main/farm.svg
  src/Images/Main/house1.jpg
  src/Images/Main/house2.jpg
  src/Images/Main/house3.jpg
  src/Images/Main/house4.jpg
  src/Images/Main/island.svg
  src/Images/Main/landscape.svg
  src/Images/Main/main.jpg
  src/Images/Main/pyramids.svg
  src/Images/Main/sealife.svg
  src/Images/Main/village.svg
  src/Images/Main/winter.svg
  src/Pages/Main/Main.Styled.js
  src/Pages/Main/Main.js
  src/Pages/Nav/Nav.Styled.js
  src/Pages/Nav/Nav.js
  src/Routes.js
Labels: Status: Accepted

#11 [13기 강수명 aircnb] 메인 페이지 반응형 구현, 리덕스 전체 페이지 적용
  public/Image/desert.svg
  public/Image/farm.svg
  public/Image/house1.jpg
  public/Image/house2.jpg
  public/Image/house3.jpg
  public/Image/house4.jpg
  public/Image/island.svg
  public/Image/landscape.svg
  public/Image/pyramids.svg
  public/Image/sealife.svg
  public/Image/village.svg
  public/Image/winter.svg
  public/data/Location/Location.json
  public/data/Main/Main.json
  src/Components/Search/Location/Location.js
  src/Components/Search/Search.js
  src/Pages/Main/Main.Styled.js
  src/Pages/Main/Main.js
  src/Pages/Nav/Nav.Styled.js
  src/Pages/Nav/Nav.js
  src/Redux/Actions/Index.js
  src/Redux/Reducers/BookReducer.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [13기 백경민] fix: HomeBooking page conflict 해결
  package-lock.json
  package.json
  src/Components/Search/Calendar/Calendar.js
  src/Components/Search/Calendar/Calendar.scss
  src/Pages/HomeBooking/Calendar.js
  src/Pages/HomeBooking/Calendar.scss
  src/Pages/HomeBooking/HomeBooking.js
  src/Pages/HomeBooking/ToggleSwitch.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#14 [13기 백경민] fix: 최종 Confilct 해결
  src/Pages/HomeBooking/HomeBooking.js
Labels: Status: 리뷰 요청

#13 [air CnB 신은선] 유동라우터 확인용 commit
  src/Components/Search/Calendar/Calendar.scss
  src/Pages/HomeDetails/Component/BedType.js
  src/Pages/HomeDetails/Component/BookingBox.js
  src/Pages/HomeDetails/Component/BookingBoxCalendar.js
  src/Pages/HomeDetails/Component/BookingBoxPersonnel.js
  src/Pages/HomeDetails/Component/ImgCarouselCon.js
  src/Pages/HomeDetails/Component/ReviewModal.js
  src/Pages/HomeDetails/Component/Reviews.js
  src/Pages/HomeDetails/Component/WishList.js
  src/Pages/HomeDetails/Component/WishListCon.js
  src/Pages/HomeDetails/HomeDetails.js
  src/Routes.js
  src/index.js
Labels: Status: Accepted

#16 [air CnB 신은선] Modify: 불필요한 코드 정리 및 인원설정 동기화 기능 추가 (merge 부탁드려요!)
  #.##
  =#.##
  src/Components/Search/Calendar/Calendar.scss
  src/Pages/HomeBooking/HomeBooking.js
  src/Pages/HomeDetails/Component/BookingBox.js
  src/Pages/HomeDetails/Component/BookingBoxPersonnel.js
  src/Pages/HomeDetails/Component/ReviewModal.js
  src/Pages/HomeDetails/HomeDetails.js
  src/Routes.js
Labels: Status: 리뷰 요청

#17 [13기 백경민] fix: 사소한 에러 수정
  src/Pages/HomeBooking/HomeBooking.js
  src/Pages/HomeBooking/ToggleSwitch.js
Labels: Status: 리뷰 요청

#9 [13기 정양효] Refactor: 코드 리뷰 반영 리팩토링, 함수명 및 불필요한 주석 등 제거
  public/Data/data.json
  public/index.html
  src/Pages/HomeBooking/HomeBooking.js
  src/Pages/HomeDetails/Component/slickSlider.scss
  src/Pages/HomeList/Components/Card.js
  src/Pages/HomeList/Components/Filters/CancellationFlexibility.js
  src/Pages/HomeList/Components/Filters/InstantBook.js
  src/Pages/HomeList/Components/Filters/MoreFilters.js
  src/Pages/HomeList/Components/Filters/TypeOfPlace.js
  src/Pages/HomeList/Components/GoogleMap.js
  src/Pages/HomeList/Components/HomeImage.js
  src/Pages/HomeList/Components/Pages.js
  src/Pages/HomeList/HomeList.js
  src/Pages/HomeList/MordalPortal.js
Labels: Status: 리뷰 요청
